-- 012_u2_capes_1534_rollback.sql
-- GENERATED by tools/u2-gen-capes.py; do not edit by hand.
-- Source: Data/Cloak.tbl, 6762 bytes, sha256 3808b5683e04e1fc044f2f45aa14f0db632eeab688b1f5986556bd064251f94f, 224 rows, 7 columns
--
-- Purpose: undo 012_u2_capes_1534.sql. Deletes only the ids recorded in
-- dbo.<Target>_U2_ADDED, then drops that log table. Rows that existed before
-- 012 was applied are never touched.
--
-- Usage:
--   sqlcmd -S .\SQLEXPRESS -E -d FDP_kn_online -b -v Target=KNIGHTS_CAPE -i db/012_u2_capes_1534_rollback.sql
--
-- The Target variable is required on purpose (no default). The script can be
-- run again: without the log table it changes nothing (removed=0).
-- The server loads the table only at start-up; restart it to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.$(Target)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(Target) not found', 16, 1);
GO

DECLARE @removed int = 0;

IF OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NOT NULL
BEGIN
    BEGIN TRANSACTION;

    -- Remove only the rows that 012 inserted.
    DELETE t
    FROM dbo.$(Target) AS t
    JOIN dbo.$(Target)_U2_ADDED AS a
        ON a.sCapeIndex = t.sCapeIndex;

    SET @removed = @@ROWCOUNT;

    DROP TABLE dbo.$(Target)_U2_ADDED;

    COMMIT TRANSACTION;
END

DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(Target));
PRINT 'removed=' + CAST(@removed AS varchar(10))
    + ' target_rows=' + CAST(@rows AS varchar(10))
    + ' log_table=' + CASE WHEN OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NULL THEN 'absent' ELSE 'present' END;
GO
