-- 012_u2_capes_1534.sql
-- GENERATED by tools/u2-gen-capes.py from the 1534 client Data/Cloak.tbl.
-- Do not edit by hand; regenerate it and run the tool with --check instead.
-- Source: Data/Cloak.tbl, 6762 bytes, sha256 3808b5683e04e1fc044f2f45aa14f0db632eeab688b1f5986556bd064251f94f, 224 rows, 7 columns
--
-- Purpose: add the capes that the 1534 client knows and the target table lacks
-- (phase U2, ADR-0068 item 4), including the long (royal) capes: the 84 rows
-- with byRanking 8..12. All values come from the client table, not from the
-- ALPHA database (its clan point prices and clan type requirements are wrong).
-- Column map: c0 sCapeIndex, c1 strName, c2 nBuyPrice, c3 nDuration,
-- c4 byGrade, c5 nBuyLoyalty, c6 byRanking. The server does not load strName;
-- Korean client names are written as "Cape <id>" (plus the pattern name).
--
-- Usage:
--   sqlcmd -S .\SQLEXPRESS -E -d FDP_kn_online -b -v Target=KNIGHTS_CAPE -i db/012_u2_capes_1534.sql
--
-- The Target variable is required on purpose (no default); it names the cape
-- table. Only ids that the target does not have are inserted; existing rows are
-- never changed. Every inserted id is recorded in dbo.<Target>_U2_ADDED so that
-- 012_u2_capes_1534_rollback.sql can remove exactly those rows. The script is
-- idempotent: running it again inserts nothing (inserted=0).
-- The server loads the table only at start-up; restart it to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.$(Target)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(Target) not found', 16, 1);
GO

IF OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NULL
CREATE TABLE dbo.$(Target)_U2_ADDED
(
    sCapeIndex smallint NOT NULL PRIMARY KEY,
    dtAdded datetime NOT NULL DEFAULT GETDATE()
);
GO

-- The 224 capes of the client table.
DECLARE @capes TABLE
(
    sCapeIndex smallint NOT NULL PRIMARY KEY,
    strName char(30) NOT NULL,
    nBuyPrice int NOT NULL,
    nDuration int NOT NULL,
    byGrade tinyint NOT NULL,
    nBuyLoyalty int NOT NULL,
    byRanking tinyint NOT NULL
);

INSERT INTO @capes (sCapeIndex, strName, nBuyPrice, nDuration, byGrade, nBuyLoyalty, byRanking)
VALUES
    (0, 'Cape 0', 0, 0, 3, 0, 2),
    (1, 'black', 20000000, 0, 3, 0, 2),
    (2, 'blue', 50000000, 0, 2, 0, 2),
    (3, 'red', 100000000, 0, 1, 0, 2),
    (4, 'purple', 20000000, 0, 3, 0, 2),
    (5, 'green', 50000000, 0, 2, 0, 2),
    (6, 'yellow', 100000000, 0, 1, 0, 2),
    (7, 'dark purple', 20000000, 0, 3, 0, 2),
    (8, 'orange', 50000000, 0, 2, 0, 2),
    (9, 'light green', 100000000, 0, 1, 0, 2),
    (10, 'black', 0, 0, 0, 36000, 3),
    (11, 'blue', 0, 0, 0, 36000, 3),
    (12, 'red', 0, 0, 0, 36000, 3),
    (13, 'purple', 0, 0, 0, 36000, 3),
    (14, 'green', 0, 0, 0, 36000, 3),
    (15, 'yellow', 0, 0, 0, 36000, 3),
    (16, 'dark purple', 0, 0, 0, 36000, 3),
    (17, 'orange', 0, 0, 0, 36000, 3),
    (18, 'light green', 0, 0, 0, 36000, 3),
    (29, 'Cape 29 iron bars', 0, 0, 0, 180000, 3),
    (30, 'Cape 30 cross', 0, 0, 0, 288000, 4),
    (31, 'Cape 31 checkered', 0, 0, 0, 432000, 5),
    (32, 'Cape 32 symmetric', 0, 0, 0, 648000, 6),
    (33, 'Cape 33 double eagle', 0, 0, 0, 864000, 7),
    (40, 'black', 0, 0, 0, 360000, 8),
    (41, 'blue', 0, 0, 0, 360000, 8),
    (42, 'red', 0, 0, 0, 360000, 8),
    (43, 'purple', 0, 0, 0, 360000, 8),
    (44, 'green', 0, 0, 0, 360000, 8),
    (45, 'yellow', 0, 0, 0, 360000, 8),
    (46, 'dark purple', 0, 0, 0, 360000, 8),
    (47, 'orange', 0, 0, 0, 360000, 8),
    (48, 'light green', 0, 0, 0, 360000, 8),
    (60, 'Cape 60', 0, 0, 0, 1080000, 8),
    (61, 'Cape 61', 0, 0, 0, 1368000, 9),
    (62, 'Cape 62', 0, 0, 0, 1728000, 10),
    (63, 'Cape 63', 0, 0, 0, 2160000, 11),
    (64, 'Cape 64', 0, 0, 0, 2880000, 12),
    (99, 'king', 0, 0, 0, 0, 2),
    (101, 'pattern01black', 40000000, 0, 3, 0, 2),
    (102, 'pattern01blue', 70000000, 0, 2, 0, 2),
    (103, 'pattern01red', 120000000, 0, 1, 0, 2),
    (104, 'pattern01purple', 40000000, 0, 3, 0, 2),
    (105, 'pattern01green', 70000000, 0, 2, 0, 2),
    (106, 'pattern01yellow', 120000000, 0, 1, 0, 2),
    (107, 'pattern01dark purple', 40000000, 0, 3, 0, 2),
    (108, 'pattern01orange', 70000000, 0, 2, 0, 2),
    (109, 'pattern01light green', 120000000, 0, 1, 0, 2),
    (110, 'black', 0, 0, 0, 36000, 3),
    (111, 'blue', 0, 0, 0, 36000, 3),
    (112, 'red', 0, 0, 0, 36000, 3),
    (113, 'purple', 0, 0, 0, 36000, 3),
    (114, 'green', 0, 0, 0, 36000, 3),
    (115, 'yellow', 0, 0, 0, 36000, 3),
    (116, 'dark purple', 0, 0, 0, 36000, 3),
    (117, 'orange', 0, 0, 0, 36000, 3),
    (118, 'light green', 0, 0, 0, 36000, 3),
    (129, 'Cape 129 iron bars', 0, 0, 0, 180000, 3),
    (130, 'Cape 130 cross', 0, 0, 0, 288000, 4),
    (131, 'Cape 131 checkered', 0, 0, 0, 432000, 5),
    (132, 'Cape 132 symmetric', 0, 0, 0, 648000, 6),
    (133, 'Cape 133 double eagle', 0, 0, 0, 864000, 7),
    (140, 'black', 0, 0, 0, 360000, 8),
    (141, 'blue', 0, 0, 0, 360000, 8),
    (142, 'red', 0, 0, 0, 360000, 8),
    (143, 'purple', 0, 0, 0, 360000, 8),
    (144, 'green', 0, 0, 0, 360000, 8),
    (145, 'yellow', 0, 0, 0, 360000, 8),
    (146, 'dark purple', 0, 0, 0, 360000, 8),
    (147, 'orange', 0, 0, 0, 360000, 8),
    (148, 'light green', 0, 0, 0, 360000, 8),
    (160, 'Cape 160', 0, 0, 0, 1080000, 8),
    (161, 'Cape 161', 0, 0, 0, 1368000, 9),
    (162, 'Cape 162', 0, 0, 0, 1728000, 10),
    (163, 'Cape 163', 0, 0, 0, 2160000, 11),
    (164, 'Cape 164', 0, 0, 0, 2880000, 12),
    (201, 'pattern02black', 50000000, 0, 3, 0, 2),
    (202, 'pattern02blue', 80000000, 0, 2, 0, 2),
    (203, 'pattern02red', 130000000, 0, 1, 0, 2),
    (204, 'pattern02purple', 50000000, 0, 3, 0, 2),
    (205, 'pattern02green', 80000000, 0, 2, 0, 2),
    (206, 'pattern02yellow', 130000000, 0, 1, 0, 2),
    (207, 'pattern02dark purple', 50000000, 0, 3, 0, 2),
    (208, 'pattern02orange', 80000000, 0, 2, 0, 2),
    (209, 'pattern02light green', 130000000, 0, 1, 0, 2),
    (210, 'black', 0, 0, 0, 36000, 3),
    (211, 'blue', 0, 0, 0, 36000, 3),
    (212, 'red', 0, 0, 0, 36000, 3),
    (213, 'purple', 0, 0, 0, 36000, 3),
    (214, 'green', 0, 0, 0, 36000, 3),
    (215, 'yellow', 0, 0, 0, 36000, 3),
    (216, 'dark purple', 0, 0, 0, 36000, 3),
    (217, 'orange', 0, 0, 0, 36000, 3),
    (218, 'light green', 0, 0, 0, 36000, 3),
    (229, 'Cape 229 iron bars', 0, 0, 0, 180000, 3),
    (230, 'Cape 230 cross', 0, 0, 0, 288000, 4),
    (231, 'Cape 231 checkered', 0, 0, 0, 432000, 5),
    (232, 'Cape 232 symmetric', 0, 0, 0, 648000, 6),
    (233, 'Cape 233 double eagle', 0, 0, 0, 864000, 7),
    (240, 'black', 0, 0, 0, 360000, 8),
    (241, 'blue', 0, 0, 0, 360000, 8),
    (242, 'red', 0, 0, 0, 360000, 8),
    (243, 'purple', 0, 0, 0, 360000, 8),
    (244, 'green', 0, 0, 0, 360000, 8),
    (245, 'yellow', 0, 0, 0, 360000, 8),
    (246, 'dark purple', 0, 0, 0, 360000, 8),
    (247, 'orange', 0, 0, 0, 360000, 8),
    (248, 'light green', 0, 0, 0, 360000, 8),
    (260, 'Cape 260', 0, 0, 0, 1080000, 8),
    (261, 'Cape 261', 0, 0, 0, 1368000, 9),
    (262, 'Cape 262', 0, 0, 0, 1728000, 10),
    (263, 'Cape 263', 0, 0, 0, 2160000, 11),
    (264, 'Cape 264', 0, 0, 0, 2880000, 12),
    (301, 'pattern03black', 60000000, 0, 3, 0, 2),
    (302, 'pattern03blue', 90000000, 0, 2, 0, 2),
    (303, 'pattern03red', 140000000, 0, 1, 0, 2),
    (304, 'pattern03purple', 60000000, 0, 3, 0, 2),
    (305, 'pattern03green', 90000000, 0, 2, 0, 2),
    (306, 'pattern03yellow', 140000000, 0, 1, 0, 2),
    (307, 'pattern03dark purple', 60000000, 0, 3, 0, 2),
    (308, 'pattern03orange', 90000000, 0, 2, 0, 2),
    (309, 'pattern03light green', 140000000, 0, 1, 0, 2),
    (310, 'black', 0, 0, 0, 36000, 3),
    (311, 'blue', 0, 0, 0, 36000, 3),
    (312, 'red', 0, 0, 0, 36000, 3),
    (313, 'purple', 0, 0, 0, 36000, 3),
    (314, 'green', 0, 0, 0, 36000, 3),
    (315, 'yellow', 0, 0, 0, 36000, 3),
    (316, 'dark purple', 0, 0, 0, 36000, 3),
    (317, 'orange', 0, 0, 0, 36000, 3),
    (318, 'light green', 0, 0, 0, 36000, 3),
    (329, 'Cape 329 iron bars', 0, 0, 0, 180000, 3),
    (330, 'Cape 330 cross', 0, 0, 0, 288000, 4),
    (331, 'Cape 331 checkered', 0, 0, 0, 432000, 5),
    (332, 'Cape 332 symmetric', 0, 0, 0, 648000, 6),
    (333, 'Cape 333 double eagle', 0, 0, 0, 864000, 7),
    (340, 'black', 0, 0, 0, 360000, 8),
    (341, 'blue', 0, 0, 0, 360000, 8),
    (342, 'red', 0, 0, 0, 360000, 8),
    (343, 'purple', 0, 0, 0, 360000, 8),
    (344, 'green', 0, 0, 0, 360000, 8),
    (345, 'yellow', 0, 0, 0, 360000, 8),
    (346, 'dark purple', 0, 0, 0, 360000, 8),
    (347, 'orange', 0, 0, 0, 360000, 8),
    (348, 'light green', 0, 0, 0, 360000, 8),
    (360, 'Cape 360', 0, 0, 0, 1080000, 8),
    (361, 'Cape 361', 0, 0, 0, 1368000, 9),
    (362, 'Cape 362', 0, 0, 0, 1728000, 10),
    (363, 'Cape 363', 0, 0, 0, 2160000, 11),
    (364, 'Cape 364', 0, 0, 0, 2880000, 12),
    (401, 'pattern04black', 70000000, 0, 3, 0, 2),
    (402, 'pattern04blue', 100000000, 0, 2, 0, 2),
    (403, 'pattern04red', 150000000, 0, 1, 0, 2),
    (404, 'pattern04purple', 70000000, 0, 3, 0, 2),
    (405, 'pattern04green', 100000000, 0, 2, 0, 2),
    (406, 'pattern04yellow', 150000000, 0, 1, 0, 2),
    (407, 'pattern04dark purple', 70000000, 0, 3, 0, 2),
    (408, 'pattern04orange', 100000000, 0, 2, 0, 2),
    (409, 'pattern04light green', 150000000, 0, 1, 0, 2),
    (410, 'black', 0, 0, 0, 36000, 3),
    (411, 'blue', 0, 0, 0, 36000, 3),
    (412, 'red', 0, 0, 0, 36000, 3),
    (413, 'purple', 0, 0, 0, 36000, 3),
    (414, 'green', 0, 0, 0, 36000, 3),
    (415, 'yellow', 0, 0, 0, 36000, 3),
    (416, 'dark purple', 0, 0, 0, 36000, 3),
    (417, 'orange', 0, 0, 0, 36000, 3),
    (418, 'light green', 0, 0, 0, 36000, 3),
    (429, 'Cape 429 iron bars', 0, 0, 0, 180000, 3),
    (430, 'Cape 430 cross', 0, 0, 0, 288000, 4),
    (431, 'Cape 431 checkered', 0, 0, 0, 432000, 5),
    (432, 'Cape 432 symmetric', 0, 0, 0, 648000, 6),
    (433, 'Cape 433 double eagle', 0, 0, 0, 864000, 7),
    (440, 'black', 0, 0, 0, 360000, 8),
    (441, 'blue', 0, 0, 0, 360000, 8),
    (442, 'red', 0, 0, 0, 360000, 8),
    (443, 'purple', 0, 0, 0, 360000, 8),
    (444, 'green', 0, 0, 0, 360000, 8),
    (445, 'yellow', 0, 0, 0, 360000, 8),
    (446, 'dark purple', 0, 0, 0, 360000, 8),
    (447, 'orange', 0, 0, 0, 360000, 8),
    (448, 'light green', 0, 0, 0, 360000, 8),
    (460, 'Cape 460', 0, 0, 0, 1080000, 8),
    (461, 'Cape 461', 0, 0, 0, 1368000, 9),
    (462, 'Cape 462', 0, 0, 0, 1728000, 10),
    (463, 'Cape 463', 0, 0, 0, 2160000, 11),
    (464, 'Cape 464', 0, 0, 0, 2880000, 12),
    (501, 'pattern05black', 80000000, 0, 3, 0, 2),
    (502, 'pattern05blue', 110000000, 0, 2, 0, 2),
    (503, 'pattern05red', 160000000, 0, 1, 0, 2),
    (504, 'pattern05purple', 80000000, 0, 3, 0, 2),
    (505, 'pattern05green', 110000000, 0, 2, 0, 2),
    (506, 'pattern05yellow', 160000000, 0, 1, 0, 2),
    (507, 'pattern05dark purple', 80000000, 0, 3, 0, 2),
    (508, 'pattern05orange', 110000000, 0, 2, 0, 2),
    (509, 'pattern05light green', 160000000, 0, 1, 0, 2),
    (510, 'black', 0, 0, 0, 36000, 3),
    (511, 'blue', 0, 0, 0, 36000, 3),
    (512, 'red', 0, 0, 0, 36000, 3),
    (513, 'purple', 0, 0, 0, 36000, 3),
    (514, 'green', 0, 0, 0, 36000, 3),
    (515, 'yellow', 0, 0, 0, 36000, 3),
    (516, 'dark purple', 0, 0, 0, 36000, 3),
    (517, 'orange', 0, 0, 0, 36000, 3),
    (518, 'light green', 0, 0, 0, 36000, 3),
    (529, 'Cape 529 iron bars', 0, 0, 0, 180000, 3),
    (530, 'Cape 530 cross', 0, 0, 0, 288000, 4),
    (531, 'Cape 531 checkered', 0, 0, 0, 432000, 5),
    (532, 'Cape 532 symmetric', 0, 0, 0, 648000, 6),
    (533, 'Cape 533 double eagle', 0, 0, 0, 864000, 7),
    (540, 'black', 0, 0, 0, 360000, 8),
    (541, 'blue', 0, 0, 0, 360000, 8),
    (542, 'red', 0, 0, 0, 360000, 8),
    (543, 'purple', 0, 0, 0, 360000, 8),
    (544, 'green', 0, 0, 0, 360000, 8),
    (545, 'yellow', 0, 0, 0, 360000, 8),
    (546, 'dark purple', 0, 0, 0, 360000, 8),
    (547, 'orange', 0, 0, 0, 360000, 8),
    (548, 'light green', 0, 0, 0, 360000, 8),
    (560, 'Cape 560', 0, 0, 0, 1080000, 8),
    (561, 'Cape 561', 0, 0, 0, 1368000, 9),
    (562, 'Cape 562', 0, 0, 0, 1728000, 10),
    (563, 'Cape 563', 0, 0, 0, 2160000, 11),
    (564, 'Cape 564', 0, 0, 0, 2880000, 12);

DECLARE @total int = (SELECT COUNT(*) FROM @capes);
DECLARE @inserted int;

BEGIN TRANSACTION;

-- Record the ids that are about to be inserted.
INSERT INTO dbo.$(Target)_U2_ADDED (sCapeIndex)
SELECT c.sCapeIndex
FROM @capes AS c
WHERE NOT EXISTS (SELECT 1 FROM dbo.$(Target) AS t WHERE t.sCapeIndex = c.sCapeIndex)
  AND NOT EXISTS (SELECT 1 FROM dbo.$(Target)_U2_ADDED AS a WHERE a.sCapeIndex = c.sCapeIndex);

-- Insert only the ids that the target does not have.
INSERT INTO dbo.$(Target) (sCapeIndex, strName, nBuyPrice, nDuration, byGrade, nBuyLoyalty, byRanking)
SELECT c.sCapeIndex, c.strName, c.nBuyPrice, c.nDuration, c.byGrade, c.nBuyLoyalty, c.byRanking
FROM @capes AS c
WHERE NOT EXISTS (SELECT 1 FROM dbo.$(Target) AS t WHERE t.sCapeIndex = c.sCapeIndex);

SET @inserted = @@ROWCOUNT;

COMMIT TRANSACTION;

PRINT 'inserted=' + CAST(@inserted AS varchar(10))
    + ' already_present=' + CAST(@total - @inserted AS varchar(10));
GO

-- Verification: one line with the row count of the target, its long capes
-- (byRanking 8..12) and the ids recorded in the log table.
DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(Target));
DECLARE @long int = (SELECT COUNT(*) FROM dbo.$(Target) WHERE byRanking BETWEEN 8 AND 12);
DECLARE @logged int = (SELECT COUNT(*) FROM dbo.$(Target)_U2_ADDED);
PRINT 'target_rows=' + CAST(@rows AS varchar(10))
    + ' long_capes=' + CAST(@long AS varchar(10))
    + ' logged=' + CAST(@logged AS varchar(10));
GO
