-- 013_u2_items_1534_rollback.sql
-- GENERATED by tools/u2-gen-alpha.py; do not edit by hand.
-- Source (values): .\SQL2019 / FDP_alpha1534 dbo.ITEM, 123720 rows read; in-scope rows sha256 6e7393054c86e72acad7f057d8fb48de989c98f9d4ce49f41b20c9a27ff8127e
-- Source (scope):  Data/item_org_us.tbl + 43 Item_Ext_<n>_us.tbl files, 1691968 bytes, combined sha256 2e1afea2f7de2b449f0ba250fe1f8b186591004699143259b5ced45322472f8f, 1401 bases, 121706 resolvable ids
-- Baseline (ours): .\SQLEXPRESS / FDP_kn_online dbo.ITEM, 85920 rows (ids recorded in dbo.ITEM_U2_ADDED not counted)
--
-- Purpose: undo 013_u2_items_1534.sql. Deletes only the ids recorded in the log
-- table(s) dbo.<target>_U2_ADDED, then drops the log table(s). Rows that existed
-- before 013 was applied are never touched.
--
-- Usage:
--   sqlcmd -S .\SQLEXPRESS -E -d FDP_kn_online -b -v Target=ITEM -i db/013_u2_items_1534_rollback.sql
--
-- The variables are required on purpose (no default). The script can be run again:
-- without a log table it changes nothing (removed=0).
-- The servers load these tables only at start-up; restart them to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.$(Target)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(Target) not found', 16, 1);
GO

DECLARE @removed int = 0;

IF OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NOT NULL
BEGIN
    BEGIN TRANSACTION;

    -- Remove only the rows that 013 inserted.
    DELETE t
    FROM dbo.$(Target) AS t
    JOIN dbo.$(Target)_U2_ADDED AS a
        ON a.Num = t.Num;

    SET @removed = @@ROWCOUNT;

    DROP TABLE dbo.$(Target)_U2_ADDED;

    COMMIT TRANSACTION;
END

DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(Target));
PRINT 'removed=' + CAST(@removed AS varchar(10))
    + ' target_rows=' + CAST(@rows AS varchar(10))
    + ' log_table=' + CASE WHEN OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NULL THEN 'absent' ELSE 'present' END;
GO
