-- 014_u2_npc_monster_1534_rollback.sql
-- GENERATED by tools/u2-gen-alpha.py; do not edit by hand.
-- Source (values): .\SQL2019 / FDP_alpha1534 dbo.K_NPC (1382 rows read, in-scope sha256 372f397b3f76d95b72a959debe13fbd7b3b8872a292e950f12832d1877ab2f21), dbo.K_MONSTER (1486 rows read, in-scope sha256 13dd3a3b02d472a46f14253981b69d74fc9c16290e38fe977f244eacb5a784af)
-- Source (scope):  Data/Npc_us.tbl, 24787 bytes, sha256 a85bd97a155f66e1a0dee541ed40b666f6038f6c7aa8297240edf53216f1e27c, 582 rows
--                  Data/Mob_us.tbl, 22334 bytes, sha256 2db1028fb62bb1e29737e56046de3a8da8c92073b71d3b7578c7d72dc6a77fc7, 855 rows
--
-- Purpose: undo 014_u2_npc_monster_1534.sql. Deletes only the ids recorded in the log
-- table(s) dbo.<target>_U2_ADDED, then drops the log table(s). Rows that existed
-- before 014 was applied are never touched.
--
-- Usage:
--   sqlcmd -S .\SQLEXPRESS -E -d FDP_kn_online -b -v NpcTarget=K_NPC -v MonTarget=K_MONSTER -i db/014_u2_npc_monster_1534_rollback.sql
--
-- The variables are required on purpose (no default). The script can be run again:
-- without a log table it changes nothing (removed=0).
-- The servers load these tables only at start-up; restart them to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.$(NpcTarget)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(NpcTarget) not found', 16, 1);
IF OBJECT_ID(N'dbo.$(MonTarget)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(MonTarget) not found', 16, 1);
GO

DECLARE @removed int = 0;

IF OBJECT_ID(N'dbo.$(NpcTarget)_U2_ADDED', N'U') IS NOT NULL
BEGIN
    BEGIN TRANSACTION;

    -- Remove only the rows that 014 inserted.
    DELETE t
    FROM dbo.$(NpcTarget) AS t
    JOIN dbo.$(NpcTarget)_U2_ADDED AS a
        ON a.sSid = t.sSid;

    SET @removed = @@ROWCOUNT;

    DROP TABLE dbo.$(NpcTarget)_U2_ADDED;

    COMMIT TRANSACTION;
END

DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(NpcTarget));
PRINT 'npc removed=' + CAST(@removed AS varchar(10))
    + ' target_rows=' + CAST(@rows AS varchar(10))
    + ' log_table=' + CASE WHEN OBJECT_ID(N'dbo.$(NpcTarget)_U2_ADDED', N'U') IS NULL THEN 'absent' ELSE 'present' END;
GO

DECLARE @removed int = 0;

IF OBJECT_ID(N'dbo.$(MonTarget)_U2_ADDED', N'U') IS NOT NULL
BEGIN
    BEGIN TRANSACTION;

    -- Remove only the rows that 014 inserted.
    DELETE t
    FROM dbo.$(MonTarget) AS t
    JOIN dbo.$(MonTarget)_U2_ADDED AS a
        ON a.sSid = t.sSid;

    SET @removed = @@ROWCOUNT;

    DROP TABLE dbo.$(MonTarget)_U2_ADDED;

    COMMIT TRANSACTION;
END

DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(MonTarget));
PRINT 'monster removed=' + CAST(@removed AS varchar(10))
    + ' target_rows=' + CAST(@rows AS varchar(10))
    + ' log_table=' + CASE WHEN OBJECT_ID(N'dbo.$(MonTarget)_U2_ADDED', N'U') IS NULL THEN 'absent' ELSE 'present' END;
GO
