-- 015_u3_moradon_1534_rollback.sql
-- GENERATED by tools/u3-gen-moradon-db.py; do not edit by hand.
-- Source (values): .\SQL2019 / FDP_alpha1534, zone 21; sha256 of the rows read d9ca91890c7a93abd2793b01385fb20a0a84948ee4b8bfe7edfca789d5720c52
--
-- Purpose: undo 015_u3_moradon_1534.sql. Writes the zone-21 rows of ZONE_INFO,
-- START_POSITION, K_OBJECTPOS and K_NPCPOS back from the dbo.<table>_Z21_U3_BACKUP
-- tables that the first run of 015_u3_moradon_1534.sql made, then drops those four
-- tables. ZONE_INFO and START_POSITION are updated in place; the K_OBJECTPOS and
-- K_NPCPOS zone-21 rows are replaced. Other zones are never touched.
--
-- Usage:
--   sqlcmd -S .\SQLEXPRESS -E -d FDP_kn1534 -b -i db/015_u3_moradon_1534_rollback.sql
--
-- The script can be run again: without the backup tables it changes nothing
-- (restored=0 backup_tables=absent). Expected output after 015_u3_moradon_1534.sql:
--   restored=1 zone_info=1 start=1 objpos=<ours> npcpos=<ours> objpos_differ=0 npcpos_differ=0 backup_tables=absent
-- The servers load these tables only at start-up; restart them to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.ZONE_INFO', N'U') IS NULL
    RAISERROR(N'table dbo.ZONE_INFO not found', 16, 1);
IF OBJECT_ID(N'dbo.START_POSITION', N'U') IS NULL
    RAISERROR(N'table dbo.START_POSITION not found', 16, 1);
IF OBJECT_ID(N'dbo.K_OBJECTPOS', N'U') IS NULL
    RAISERROR(N'table dbo.K_OBJECTPOS not found', 16, 1);
IF OBJECT_ID(N'dbo.K_NPCPOS', N'U') IS NULL
    RAISERROR(N'table dbo.K_NPCPOS not found', 16, 1);
GO

DECLARE @backups int =
    CASE WHEN OBJECT_ID(N'dbo.ZONE_INFO_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END
    + CASE WHEN OBJECT_ID(N'dbo.START_POSITION_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END
    + CASE WHEN OBJECT_ID(N'dbo.K_OBJECTPOS_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END
    + CASE WHEN OBJECT_ID(N'dbo.K_NPCPOS_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END;

IF @backups NOT IN (0, 4)
BEGIN
    RAISERROR(N'%d of the 4 _Z21_U3_BACKUP tables exist (expected 0 or 4); nothing changed', 16, 1, @backups);
    RETURN;
END

IF @backups = 0
BEGIN
    PRINT 'restored=0 backup_tables=absent';
    RETURN;
END

DECLARE @zone_info_rows int = (SELECT COUNT(*) FROM dbo.ZONE_INFO WHERE ZoneNo = 21);
DECLARE @start_rows int = (SELECT COUNT(*) FROM dbo.START_POSITION WHERE ZoneID = 21);
DECLARE @zone_info_backup int = (SELECT COUNT(*) FROM dbo.ZONE_INFO_Z21_U3_BACKUP);
DECLARE @start_backup int = (SELECT COUNT(*) FROM dbo.START_POSITION_Z21_U3_BACKUP);

IF @zone_info_rows <> 1 OR @start_rows <> 1 OR @zone_info_backup <> 1 OR @start_backup <> 1
BEGIN
    RAISERROR(N'zone 21 ZONE_INFO/START_POSITION rows %d/%d, backup rows %d/%d (expected 1 each); nothing changed', 16, 1,
        @zone_info_rows, @start_rows, @zone_info_backup, @start_backup);
    RETURN;
END

BEGIN TRANSACTION;

UPDATE t SET
    t.ServerNo = b.ServerNo,
    t.strZoneName = b.strZoneName,
    t.InitX = b.InitX,
    t.InitZ = b.InitZ,
    t.InitY = b.InitY,
    t.Type = b.Type,
    t.RoomEvent = b.RoomEvent,
    t.bz = b.bz
FROM dbo.ZONE_INFO AS t
JOIN dbo.ZONE_INFO_Z21_U3_BACKUP AS b
    ON b.ZoneNo = t.ZoneNo
WHERE t.ZoneNo = 21;

UPDATE t SET
    t.sKarusX = b.sKarusX,
    t.sKarusZ = b.sKarusZ,
    t.sElmoradX = b.sElmoradX,
    t.sElmoradZ = b.sElmoradZ,
    t.sKarusGateX = b.sKarusGateX,
    t.sKarusGateZ = b.sKarusGateZ,
    t.sElmoGateX = b.sElmoGateX,
    t.sElmoGateZ = b.sElmoGateZ,
    t.bRangeX = b.bRangeX,
    t.bRangeZ = b.bRangeZ
FROM dbo.START_POSITION AS t
JOIN dbo.START_POSITION_Z21_U3_BACKUP AS b
    ON b.ZoneID = t.ZoneID
WHERE t.ZoneID = 21;

DELETE FROM dbo.K_OBJECTPOS WHERE ZoneID = 21;

INSERT INTO dbo.K_OBJECTPOS (
    ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
)
SELECT
    ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
FROM dbo.K_OBJECTPOS_Z21_U3_BACKUP;

DELETE FROM dbo.K_NPCPOS WHERE ZoneID = 21;

INSERT INTO dbo.K_NPCPOS (
    ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber, LeftX,
    TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ, NumNPC, RegTime,
    byDirection, DotCnt, path
)
SELECT
    ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber, LeftX,
    TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ, NumNPC, RegTime,
    byDirection, DotCnt, path
FROM dbo.K_NPCPOS_Z21_U3_BACKUP;

DECLARE @zone_info int = (SELECT COUNT(*) FROM (
    SELECT
        ServerNo, ZoneNo, strZoneName, InitX, InitZ, InitY, Type, RoomEvent, bz
    FROM dbo.ZONE_INFO WHERE ZoneNo = 21
    INTERSECT
    SELECT
        ServerNo, ZoneNo, strZoneName, InitX, InitZ, InitY, Type, RoomEvent, bz
    FROM dbo.ZONE_INFO_Z21_U3_BACKUP) AS d);
DECLARE @start int = (SELECT COUNT(*) FROM (
    SELECT
        ZoneID, sKarusX, sKarusZ, sElmoradX, sElmoradZ, sKarusGateX, sKarusGateZ,
        sElmoGateX, sElmoGateZ, bRangeX, bRangeZ
    FROM dbo.START_POSITION WHERE ZoneID = 21
    INTERSECT
    SELECT
        ZoneID, sKarusX, sKarusZ, sElmoradX, sElmoradZ, sKarusGateX, sKarusGateZ,
        sElmoGateX, sElmoGateZ, bRangeX, bRangeZ
    FROM dbo.START_POSITION_Z21_U3_BACKUP) AS d);
DECLARE @objpos int = (SELECT COUNT(*) FROM dbo.K_OBJECTPOS WHERE ZoneID = 21);
DECLARE @npcpos int = (SELECT COUNT(*) FROM dbo.K_NPCPOS WHERE ZoneID = 21);
DECLARE @obj_differ int =
    (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM dbo.K_OBJECTPOS_Z21_U3_BACKUP
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
        EXCEPT
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM dbo.K_OBJECTPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife) AS d)
    + (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM dbo.K_OBJECTPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
        EXCEPT
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM dbo.K_OBJECTPOS_Z21_U3_BACKUP
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife) AS d);
DECLARE @npc_differ int =
    (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM dbo.K_NPCPOS_Z21_U3_BACKUP
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))
        EXCEPT
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM dbo.K_NPCPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))) AS d)
    + (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM dbo.K_NPCPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))
        EXCEPT
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM dbo.K_NPCPOS_Z21_U3_BACKUP
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))) AS d);

IF @zone_info <> 1 OR @start <> 1 OR @obj_differ <> 0 OR @npc_differ <> 0
BEGIN
    ROLLBACK TRANSACTION;
    RAISERROR(N'restored rows differ from the backup; nothing changed', 16, 1);
    RETURN;
END

DROP TABLE dbo.ZONE_INFO_Z21_U3_BACKUP;
DROP TABLE dbo.START_POSITION_Z21_U3_BACKUP;
DROP TABLE dbo.K_OBJECTPOS_Z21_U3_BACKUP;
DROP TABLE dbo.K_NPCPOS_Z21_U3_BACKUP;

COMMIT TRANSACTION;

PRINT 'restored=1 zone_info=' + CAST(@zone_info AS varchar(10))
    + ' start=' + CAST(@start AS varchar(10))
    + ' objpos=' + CAST(@objpos AS varchar(10))
    + ' npcpos=' + CAST(@npcpos AS varchar(10))
    + ' objpos_differ=' + CAST(@obj_differ AS varchar(10))
    + ' npcpos_differ=' + CAST(@npc_differ AS varchar(10))
    + ' backup_tables=' + CASE WHEN OBJECT_ID(N'dbo.K_NPCPOS_Z21_U3_BACKUP', N'U') IS NULL THEN 'absent' ELSE 'present' END;
GO
