-- 015_u3_moradon_1534.sql
-- GENERATED by tools/u3-gen-moradon-db.py from the ALPHA database; do not edit by hand.
-- Regenerate it and run the tool with --check instead.
-- Source (values): .\SQL2019 / FDP_alpha1534, zone 21: ZONE_INFO 1 row, START_POSITION 1 row,
--                  K_OBJECTPOS 33 rows, K_NPCPOS 123 rows; sha256 of the rows read d9ca91890c7a93abd2793b01385fb20a0a84948ee4b8bfe7edfca789d5720c52
-- Ids checked in:  .\SQLEXPRESS / FDP_kn_online dbo.K_NPC 603 rows, dbo.K_MONSTER 850 rows
-- Baseline (ours): .\SQLEXPRESS / FDP_kn_online, zone 21 (live tables):
--                  ZONE_INFO 'moradon_20060124.smd' Init 31200/40200/0 RoomEvent 21;
--                  START_POSITION 306/352 and 306/352, gates 10/10/0/0, range 0/0;
--                  K_OBJECTPOS 3 rows (4013, 4014, 5001); K_NPCPOS 138 rows, 58 ids
--
-- Purpose: the database side of the new Moradon (zone 21) for the 1534 client (phase
-- U3, ADR-0068 addendum 2; docs/reports/u0-1534/G-yeni-moradon-smd.md 5 and 7). Apply it
-- ONLY to the separate 1534 database copy (e.g. FDP_kn1534): zone-21 data is chosen by
-- the database, and the 1453 client must keep the old Moradon in FDP_kn_online. The
-- script refuses to run in a database named FDP_kn_online.
--
-- Changes, zone 21 only, in one transaction:
--   ZONE_INFO       strZoneName 'moradon_1534.smd' (the server map of plan U3-01);
--                   InitX/InitZ/InitY 81590/53079/469 and RoomEvent 0 (ALPHA's values; with
--                   RoomEvent 0 the AIServer no longer loads 21.aievt, G report 6).
--                   ServerNo, Type and bz stay ours.
--   START_POSITION  both nations 817/530, bRangeX/bRangeZ 10/10, the four gate columns 0
--                   (ALPHA's row). Ours had the range in the gate columns and bRange 0.
--   K_OBJECTPOS     our rows are replaced by ALPHA's 3 rows:
--                   4013 (Type 5, Belong 2, ControlNpcID 212) at (837.36, 526.76)
--                   4014 (Type 5, Belong 1, ControlNpcID 211) at (797.70, 526.88)
--                   5001 (Type 8, Belong 1, ControlNpcID 0) at (816.14, 607.17)
--                   Not copied: the soccer objects 1019, 1020, 1021, 1022 (ADR-0068 addendum 2
--                   item 3; sea in this client), and 26 rows of Type 50 (effects,
--                   sIndex 0): that type is not in our enum ObjectType (shared/packets.h),
--                   no server code uses it, and our database has no such row elsewhere.
--   K_NPCPOS        our rows are replaced by ALPHA's 123 rows: 75 ids, NumNPC sum 423;
--                   48 NPC rows (ActType >= 100 -> K_NPC, 38 ids) and 75 monster rows
--                   (-> K_MONSTER, 37 ids). Every id exists in our K_NPC/K_MONSTER;
--                   db/014 (U2) adds 18 of them:
--                   1056, 1057, 1058, 1180, 13016, 19001, 19002, 19003, 19004, 19005,
--                   19006, 19067, 19068, 19069, 19070, 19071, 19072, 29001.
--                   The script checks this again in the target database and changes
--                   nothing if an id is missing (the AIServer would stop loading spawns).
--                   Values are ALPHA's, copied by column name. In 123 rows ALPHA's LimitMinX
--                   holds TopZ and LimitMinZ holds LeftX; they are copied as they are: the
--                   AIServer reads Limit* only when DungeonFamily > 0 (AIServer/ServerDlg.cpp),
--                   and DungeonFamily is 0 in every row. 13 rows carry the 4-character
--                   text 'NULL' in path, as in ALPHA; 2 of them have DotCnt > 0 with ActType
--                   100 (standing NPCs, the path is not used).
-- Bounds: START_POSITION with its range, ZONE_INFO Init / 100, the K_OBJECTPOS positions,
-- every K_NPCPOS rectangle corner and path point lie in 0..1023 (map 1024 m).
-- Not part of this script: Lua (U3-03), a USERDATA position reset (owner decision),
-- warp fees (in the SMD, U3-01).
--
-- Backups: the first run copies the zone-21 rows of the four tables into
-- dbo.<table>_Z21_U3_BACKUP (ZONE_INFO, START_POSITION, K_OBJECTPOS, K_NPCPOS);
-- a later run leaves them as they are (backup=kept).
-- 015_u3_moradon_1534_rollback.sql writes them back and drops them.
--
-- Usage:
--   sqlcmd -S .\SQLEXPRESS -E -d FDP_kn1534 -b -i db/015_u3_moradon_1534.sql
--
-- The script is idempotent: running it again gives the same final state. Expected output:
--   backup=created deleted_objpos=<ours> deleted_npcpos=<ours> inserted_objpos=3 inserted_npcpos=123
--   zone_info=1 start=1 objpos=3 npcpos=123 objpos_differ=0 npcpos_differ=0
-- (backup=kept on a later run). The servers load these tables only at start-up: restart
-- GameServer and AIServer, with Map/moradon_1534.smd (U3-01) in place.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-- Stop early under -b; the main batch below checks everything again.
IF DB_NAME() = N'FDP_kn_online'
    RAISERROR(N'this script is for the 1534 database copy, not FDP_kn_online (ADR-0068 addendum 2)', 16, 1);
IF OBJECT_ID(N'dbo.ZONE_INFO', N'U') IS NULL
    RAISERROR(N'table dbo.ZONE_INFO not found', 16, 1);
IF OBJECT_ID(N'dbo.START_POSITION', N'U') IS NULL
    RAISERROR(N'table dbo.START_POSITION not found', 16, 1);
IF OBJECT_ID(N'dbo.K_OBJECTPOS', N'U') IS NULL
    RAISERROR(N'table dbo.K_OBJECTPOS not found', 16, 1);
IF OBJECT_ID(N'dbo.K_NPCPOS', N'U') IS NULL
    RAISERROR(N'table dbo.K_NPCPOS not found', 16, 1);
GO

-- Staging table for the 3 object rows (dropped at the end of the script).
IF OBJECT_ID(N'tempdb..#u3_objpos', N'U') IS NOT NULL
    DROP TABLE #u3_objpos;
CREATE TABLE #u3_objpos
(
    ZoneID smallint NOT NULL,
    Belong tinyint NOT NULL,
    sIndex smallint NOT NULL,
    Type tinyint NOT NULL,
    ControlNpcID smallint NOT NULL,
    Status tinyint NOT NULL,
    PosX float NOT NULL,
    PosY float NOT NULL,
    PosZ float NOT NULL,
    byLife tinyint NOT NULL
);

INSERT INTO #u3_objpos (
    ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
)
VALUES
    (21, 2, 4013, 5, 212, 1, 837.36E0, 4.78032E0, 526.757E0, 1),
    (21, 1, 4014, 5, 211, 1, 797.696E0, 4.84992E0, 526.879E0, 1),
    (21, 1, 5001, 8, 0, 1, 816.136E0, 13.648E0, 607.173E0, 1);
GO

-- Staging table for the 123 spawn rows (dropped at the end of the script).
IF OBJECT_ID(N'tempdb..#u3_npcpos', N'U') IS NOT NULL
    DROP TABLE #u3_npcpos;
CREATE TABLE #u3_npcpos
(
    ZoneID smallint NOT NULL,
    NpcID int NOT NULL,
    ActType tinyint NOT NULL,
    RegenType tinyint NOT NULL,
    DungeonFamily tinyint NOT NULL,
    SpecialType tinyint NOT NULL,
    TrapNumber tinyint NOT NULL,
    LeftX int NOT NULL,
    TopZ int NOT NULL,
    RightX int NOT NULL,
    BottomZ int NOT NULL,
    LimitMinX int NOT NULL,
    LimitMinZ int NOT NULL,
    LimitMaxX int NOT NULL,
    LimitMaxZ int NOT NULL,
    NumNPC tinyint NOT NULL,
    RegTime smallint NOT NULL,
    byDirection tinyint NOT NULL,
    DotCnt tinyint NOT NULL,
    path varchar(max) COLLATE DATABASE_DEFAULT NULL
);

INSERT INTO #u3_npcpos (
    ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber, LeftX,
    TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ, NumNPC, RegTime,
    byDirection, DotCnt, path
)
VALUES
    (21, 150, 1, 0, 0, 0, 0, 597, 341, 614, 326, 341, 597, 614, 326, 5, 30, 0, 0, NULL),
    (21, 150, 1, 0, 0, 0, 0, 616, 341, 633, 326, 341, 616, 633, 326, 5, 30, 0, 0, NULL),
    (21, 155, 1, 0, 0, 0, 0, 602, 306, 619, 291, 306, 602, 619, 291, 5, 30, 0, 0, NULL),
    (21, 155, 1, 0, 0, 0, 0, 627, 311, 644, 296, 311, 627, 644, 296, 5, 30, 0, 0, NULL),
    (21, 159, 1, 0, 0, 0, 0, 628, 273, 645, 258, 273, 628, 645, 258, 5, 30, 0, 0, NULL),
    (21, 159, 1, 0, 0, 0, 0, 658, 291, 675, 276, 291, 658, 675, 276, 5, 30, 0, 0, NULL),
    (21, 250, 1, 0, 0, 0, 0, 535, 381, 552, 366, 381, 535, 552, 366, 5, 30, 0, 0, NULL),
    (21, 250, 1, 0, 0, 0, 0, 535, 414, 552, 399, 414, 535, 552, 399, 5, 30, 0, 0, NULL),
    (21, 251, 1, 0, 0, 0, 0, 502, 415, 519, 400, 415, 502, 519, 400, 5, 30, 0, 0, NULL),
    (21, 251, 1, 0, 0, 0, 0, 506, 436, 523, 421, 436, 506, 523, 421, 5, 30, 0, 0, NULL),
    (21, 253, 1, 0, 0, 0, 0, 382, 405, 399, 390, 405, 382, 399, 390, 5, 30, 0, 0, NULL),
    (21, 253, 1, 0, 0, 0, 0, 414, 405, 431, 390, 405, 414, 431, 390, 5, 30, 0, 0, NULL),
    (21, 254, 1, 0, 0, 0, 0, 443, 327, 460, 312, 327, 443, 460, 312, 5, 30, 0, 0, NULL),
    (21, 254, 1, 0, 0, 0, 0, 457, 350, 474, 335, 350, 457, 474, 335, 5, 30, 0, 0, NULL),
    (21, 256, 1, 0, 0, 0, 0, 338, 775, 355, 760, 775, 338, 355, 760, 5, 30, 0, 0, NULL),
    (21, 256, 1, 0, 0, 0, 0, 341, 802, 358, 787, 802, 341, 358, 787, 5, 30, 0, 0, NULL),
    (21, 257, 1, 0, 0, 0, 0, 385, 433, 402, 418, 433, 385, 402, 418, 5, 30, 0, 0, NULL),
    (21, 257, 1, 0, 0, 0, 0, 415, 431, 432, 416, 431, 415, 432, 416, 5, 30, 0, 0, NULL),
    (21, 350, 1, 0, 0, 0, 0, 566, 260, 583, 245, 260, 566, 583, 245, 5, 30, 0, 0, NULL),
    (21, 350, 1, 0, 0, 0, 0, 577, 268, 594, 253, 268, 577, 594, 253, 5, 30, 0, 0, NULL),
    (21, 351, 1, 0, 0, 0, 0, 534, 227, 551, 212, 227, 534, 551, 212, 5, 30, 0, 0, NULL),
    (21, 351, 1, 0, 0, 0, 0, 546, 246, 563, 231, 246, 546, 563, 231, 5, 30, 0, 0, NULL),
    (21, 353, 1, 0, 0, 0, 0, 429, 614, 446, 599, 614, 429, 446, 599, 5, 30, 0, 0, NULL),
    (21, 353, 1, 0, 0, 0, 0, 434, 635, 451, 620, 635, 434, 451, 620, 5, 30, 0, 0, NULL),
    (21, 354, 1, 0, 0, 0, 0, 464, 595, 481, 580, 595, 464, 481, 580, 5, 30, 0, 0, NULL),
    (21, 354, 1, 0, 0, 0, 0, 483, 605, 500, 590, 605, 483, 500, 590, 5, 30, 0, 0, NULL),
    (21, 450, 1, 0, 0, 0, 0, 559, 565, 576, 550, 565, 559, 576, 550, 5, 30, 0, 0, NULL),
    (21, 450, 1, 0, 0, 0, 0, 586, 573, 603, 558, 573, 586, 603, 558, 5, 30, 0, 0, NULL),
    (21, 452, 1, 0, 0, 0, 0, 185, 746, 202, 731, 746, 185, 202, 731, 5, 30, 0, 0, NULL),
    (21, 550, 1, 0, 0, 0, 0, 385, 464, 402, 449, 464, 385, 402, 449, 5, 30, 0, 0, NULL),
    (21, 550, 1, 0, 0, 0, 0, 410, 462, 427, 447, 462, 410, 427, 447, 5, 30, 0, 0, NULL),
    (21, 551, 1, 0, 0, 0, 0, 457, 666, 474, 651, 666, 457, 474, 651, 5, 30, 0, 0, NULL),
    (21, 551, 1, 0, 0, 0, 0, 479, 694, 496, 679, 694, 479, 496, 679, 5, 30, 0, 0, NULL),
    (21, 552, 1, 0, 0, 0, 0, 502, 724, 519, 709, 724, 502, 519, 709, 5, 30, 0, 0, NULL),
    (21, 552, 1, 0, 0, 0, 0, 534, 689, 551, 674, 689, 534, 551, 674, 5, 30, 0, 0, NULL),
    (21, 553, 1, 0, 0, 0, 0, 538, 851, 555, 836, 851, 538, 555, 836, 5, 30, 0, 0, NULL),
    (21, 553, 1, 0, 0, 0, 0, 565, 854, 582, 839, 854, 565, 582, 839, 5, 30, 0, 0, NULL),
    (21, 554, 1, 0, 0, 0, 0, 477, 782, 494, 767, 782, 477, 494, 767, 5, 30, 0, 0, NULL),
    (21, 554, 1, 0, 0, 0, 0, 502, 781, 519, 766, 781, 502, 519, 766, 5, 30, 0, 0, NULL),
    (21, 555, 1, 0, 0, 0, 0, 522, 803, 539, 788, 803, 522, 539, 788, 5, 30, 0, 0, NULL),
    (21, 555, 1, 0, 0, 0, 0, 549, 778, 566, 763, 778, 549, 566, 763, 5, 30, 0, 0, NULL),
    (21, 603, 100, 0, 0, 0, 0, 700, 525, 700, 525, 525, 700, 700, 525, 1, 30, 0, 0, NULL),
    (21, 650, 1, 0, 0, 0, 0, 454, 824, 471, 809, 824, 454, 471, 809, 5, 30, 0, 0, NULL),
    (21, 650, 1, 0, 0, 0, 0, 488, 829, 505, 814, 829, 488, 505, 814, 5, 30, 0, 0, NULL),
    (21, 652, 1, 0, 0, 0, 0, 452, 879, 469, 864, 879, 452, 469, 864, 5, 30, 0, 0, NULL),
    (21, 652, 1, 0, 0, 0, 0, 478, 876, 495, 861, 876, 478, 495, 861, 5, 30, 0, 0, NULL),
    (21, 653, 1, 0, 0, 0, 0, 242, 488, 259, 473, 488, 242, 259, 473, 5, 30, 0, 0, NULL),
    (21, 653, 1, 0, 0, 0, 0, 310, 174, 327, 159, 174, 310, 327, 159, 5, 30, 0, 0, NULL),
    (21, 750, 1, 0, 0, 0, 0, 624, 402, 641, 387, 402, 624, 641, 387, 5, 30, 0, 0, NULL),
    (21, 750, 1, 0, 0, 0, 0, 637, 429, 654, 414, 429, 637, 654, 414, 5, 30, 0, 0, NULL),
    (21, 752, 1, 0, 0, 0, 0, 597, 436, 614, 421, 436, 597, 614, 421, 5, 30, 0, 0, NULL),
    (21, 752, 1, 0, 0, 0, 0, 603, 392, 620, 377, 392, 603, 620, 377, 5, 30, 0, 0, NULL),
    (21, 850, 1, 0, 0, 0, 0, 603, 463, 620, 448, 463, 603, 620, 448, 5, 30, 0, 0, NULL),
    (21, 850, 1, 0, 0, 0, 0, 632, 465, 649, 450, 465, 632, 649, 450, 5, 30, 0, 0, NULL),
    (21, 852, 1, 0, 0, 0, 0, 590, 479, 607, 464, 479, 590, 607, 464, 5, 30, 0, 0, NULL),
    (21, 852, 1, 0, 0, 0, 0, 615, 481, 632, 466, 481, 615, 632, 466, 5, 30, 0, 0, NULL),
    (21, 950, 1, 0, 0, 0, 0, 394, 685, 411, 670, 685, 394, 411, 670, 5, 30, 0, 0, NULL),
    (21, 950, 1, 0, 0, 0, 0, 403, 704, 420, 689, 704, 403, 420, 689, 5, 30, 0, 0, NULL),
    (21, 953, 1, 0, 0, 0, 0, 408, 760, 425, 745, 760, 408, 425, 745, 5, 30, 0, 0, NULL),
    (21, 953, 1, 0, 0, 0, 0, 409, 734, 426, 719, 734, 409, 426, 719, 5, 30, 0, 0, NULL),
    (21, 954, 1, 0, 0, 0, 0, 402, 813, 419, 798, 813, 402, 419, 798, 5, 30, 0, 0, NULL),
    (21, 954, 1, 0, 0, 0, 0, 406, 790, 423, 775, 790, 406, 423, 775, 5, 30, 0, 0, NULL),
    (21, 1056, 1, 0, 0, 0, 0, 283, 937, 300, 922, 937, 283, 300, 922, 5, 30, 0, 0, NULL),
    (21, 1056, 1, 0, 0, 0, 0, 305, 960, 322, 945, 960, 305, 322, 945, 5, 30, 0, 0, NULL),
    (21, 1057, 1, 0, 0, 0, 0, 348, 949, 365, 934, 949, 348, 365, 934, 5, 30, 0, 0, NULL),
    (21, 1057, 1, 0, 0, 0, 0, 351, 980, 368, 965, 980, 351, 368, 965, 5, 30, 0, 0, NULL),
    (21, 1058, 1, 0, 0, 0, 0, 287, 891, 304, 876, 891, 287, 304, 876, 5, 30, 0, 0, NULL),
    (21, 1058, 1, 0, 0, 0, 0, 312, 901, 329, 886, 901, 312, 329, 886, 5, 30, 0, 0, NULL),
    (21, 1154, 1, 0, 0, 0, 0, 153, 864, 170, 849, 864, 153, 170, 849, 5, 30, 0, 0, NULL),
    (21, 1154, 1, 0, 0, 0, 0, 155, 806, 172, 791, 806, 155, 172, 791, 5, 30, 0, 0, NULL),
    (21, 1154, 1, 0, 0, 0, 0, 156, 952, 173, 937, 952, 156, 173, 937, 5, 30, 0, 0, NULL),
    (21, 1154, 1, 0, 0, 0, 0, 191, 917, 208, 902, 917, 191, 208, 902, 5, 30, 0, 0, NULL),
    (21, 1180, 1, 0, 0, 0, 0, 349, 861, 366, 846, 861, 349, 366, 846, 5, 30, 0, 0, NULL),
    (21, 1180, 1, 0, 0, 0, 0, 373, 881, 390, 866, 881, 373, 390, 866, 5, 30, 0, 0, NULL),
    (21, 1671, 1, 0, 0, 0, 0, 323, 712, 340, 697, 712, 323, 340, 697, 5, 30, 0, 0, NULL),
    (21, 1671, 1, 0, 0, 0, 0, 328, 687, 345, 672, 687, 328, 345, 672, 5, 30, 0, 0, NULL),
    (21, 11021, 100, 0, 0, 0, 0, 836, 491, 836, 491, 491, 836, 836, 491, 1, 3600, 0, 2, 'NULL'),
    (21, 11021, 100, 0, 0, 0, 0, 842, 491, 842, 491, 491, 842, 842, 491, 1, 3600, 0, 2, 'NULL'),
    (21, 13001, 100, 0, 0, 0, 0, 697, 620, 697, 620, 620, 697, 697, 620, 1, 4400, 45, 0, NULL),
    (21, 13005, 100, 0, 0, 0, 0, 48, 897, 48, 897, 897, 48, 48, 897, 1, 4400, 43, 0, NULL),
    (21, 13005, 100, 0, 0, 0, 0, 377, 572, 377, 572, 572, 377, 377, 572, 1, 4400, 115, 0, NULL),
    (21, 13005, 100, 0, 0, 0, 0, 855, 561, 855, 561, 561, 855, 855, 561, 1, 4400, 90, 0, NULL),
    (21, 13006, 100, 0, 0, 0, 0, 786, 595, 786, 595, 595, 786, 786, 595, 1, 4400, 45, 0, NULL),
    (21, 13007, 100, 0, 0, 0, 0, 84, 923, 84, 923, 923, 84, 84, 923, 1, 4400, 100, 0, NULL),
    (21, 13007, 100, 0, 0, 0, 0, 419, 545, 419, 545, 545, 419, 419, 545, 1, 4400, 135, 0, NULL),
    (21, 13007, 100, 0, 0, 0, 0, 868, 530, 868, 530, 530, 868, 868, 530, 1, 4400, 0, 0, NULL),
    (21, 13008, 100, 0, 0, 0, 0, 786, 587, 786, 587, 587, 786, 786, 587, 1, 4400, 45, 0, NULL),
    (21, 13009, 100, 0, 0, 0, 0, 749, 529, 749, 529, 529, 749, 749, 529, 1, 4400, 0, 0, NULL),
    (21, 13013, 100, 0, 0, 0, 0, 828, 545, 828, 545, 545, 828, 828, 545, 1, 4400, 162, 0, NULL),
    (21, 13015, 100, 0, 0, 0, 0, 815, 921, 815, 921, 921, 815, 815, 921, 1, 4400, 90, 0, NULL),
    (21, 13016, 100, 0, 0, 0, 0, 887, 477, 887, 477, 477, 887, 887, 477, 1, 4400, 135, 0, NULL),
    (21, 14301, 100, 0, 0, 0, 0, 729, 580, 729, 580, 580, 729, 729, 580, 1, 4400, 0, 0, NULL),
    (21, 14401, 100, 0, 0, 0, 0, 816, 626, 816, 626, 626, 816, 816, 626, 1, 4400, 180, 0, NULL),
    (21, 14402, 100, 0, 0, 0, 0, 691, 428, 691, 428, 428, 691, 691, 428, 1, 4400, 90, 0, NULL),
    (21, 15002, 100, 0, 0, 0, 0, 757, 479, 757, 479, 479, 757, 757, 479, 1, 4400, 90, 0, 'NULL'),
    (21, 16047, 100, 0, 0, 0, 0, 802, 772, 802, 772, 772, 802, 802, 772, 1, 4400, 90, 0, NULL),
    (21, 16079, 100, 0, 0, 0, 0, 817, 521, 817, 521, 521, 817, 817, 521, 1, 4400, 180, 0, NULL),
    (21, 16085, 100, 0, 0, 0, 0, 907, 553, 907, 553, 553, 907, 907, 553, 1, 4400, 155, 0, NULL),
    (21, 16096, 100, 0, 0, 0, 0, 770, 648, 770, 648, 648, 770, 770, 648, 1, 4400, 45, 0, NULL),
    (21, 16097, 100, 0, 0, 0, 0, 409, 555, 409, 555, 555, 409, 409, 555, 1, 4400, 93, 0, NULL),
    (21, 16097, 100, 0, 0, 0, 0, 859, 648, 859, 648, 648, 859, 859, 648, 1, 4400, 135, 0, NULL),
    (21, 18004, 100, 0, 0, 0, 0, 816, 690, 816, 690, 690, 816, 816, 690, 1, 4400, 90, 0, NULL),
    (21, 18005, 100, 0, 0, 0, 0, 822, 657, 822, 657, 657, 822, 822, 657, 1, 4400, 90, 0, NULL),
    (21, 19001, 100, 0, 0, 0, 0, 866, 402, 866, 402, 402, 866, 866, 402, 1, 1800, 0, 0, 'NULL'),
    (21, 19002, 100, 0, 0, 0, 0, 393, 550, 393, 550, 550, 393, 393, 550, 1, 4400, 100, 0, NULL),
    (21, 19003, 100, 0, 0, 0, 0, 425, 528, 425, 528, 528, 425, 425, 528, 1, 4400, 100, 0, NULL),
    (21, 19004, 100, 0, 0, 0, 0, 359, 535, 359, 535, 535, 359, 359, 535, 1, 4400, 35, 0, NULL),
    (21, 19005, 100, 0, 0, 0, 0, 855, 593, 855, 593, 593, 855, 855, 593, 1, 4400, 145, 0, NULL),
    (21, 19006, 100, 0, 0, 0, 0, 719, 428, 719, 428, 428, 719, 719, 428, 1, 4400, 100, 0, NULL),
    (21, 19067, 100, 0, 0, 0, 0, 758, 416, 758, 416, 416, 758, 758, 416, 1, 30, 90, 0, 'NULL'),
    (21, 19067, 100, 0, 0, 0, 0, 758, 422, 758, 422, 422, 758, 758, 422, 1, 30, 90, 0, 'NULL'),
    (21, 19068, 100, 0, 0, 0, 0, 767, 416, 767, 416, 416, 767, 767, 416, 1, 30, 90, 0, 'NULL'),
    (21, 19068, 100, 0, 0, 0, 0, 767, 422, 767, 422, 422, 767, 767, 422, 1, 30, 90, 0, 'NULL'),
    (21, 19069, 100, 0, 0, 0, 0, 776, 416, 776, 416, 416, 776, 776, 416, 1, 30, 90, 0, 'NULL'),
    (21, 19069, 100, 0, 0, 0, 0, 776, 422, 776, 422, 422, 776, 776, 422, 1, 30, 90, 0, 'NULL'),
    (21, 19070, 102, 0, 0, 0, 0, 758, 406, 758, 406, 406, 758, 758, 406, 1, 30, 90, 2, '0758040607760406'),
    (21, 19071, 102, 0, 0, 0, 0, 758, 398, 758, 398, 398, 758, 758, 398, 1, 30, 90, 2, '0758039807760398'),
    (21, 19072, 102, 0, 0, 0, 0, 758, 390, 758, 390, 390, 758, 758, 390, 1, 30, 90, 2, '0758039007760390'),
    (21, 21021, 100, 0, 0, 0, 0, 795, 491, 795, 491, 491, 795, 795, 491, 1, 30, 0, 0, 'NULL'),
    (21, 21021, 100, 0, 0, 0, 0, 801, 491, 801, 491, 491, 801, 801, 491, 1, 30, 0, 0, 'NULL'),
    (21, 22301, 100, 0, 0, 0, 0, 821, 607, 821, 607, 607, 821, 821, 607, 1, 4400, 110, 0, NULL),
    (21, 24414, 100, 0, 0, 0, 0, 343, 880, 343, 880, 880, 343, 343, 880, 1, 4400, 45, 0, NULL),
    (21, 29001, 100, 0, 0, 0, 0, 788, 369, 788, 369, 369, 788, 788, 369, 1, 1800, 0, 0, 'NULL');
GO

-- Checks, backups and changes in one batch and one transaction. Nothing is changed
-- when a check fails (also when sqlcmd runs without -b).
DECLARE @obj_staged int = (SELECT COUNT(*) FROM #u3_objpos);
DECLARE @npc_staged int = (SELECT COUNT(*) FROM #u3_npcpos);
DECLARE @backups int =
    CASE WHEN OBJECT_ID(N'dbo.ZONE_INFO_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END
    + CASE WHEN OBJECT_ID(N'dbo.START_POSITION_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END
    + CASE WHEN OBJECT_ID(N'dbo.K_OBJECTPOS_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END
    + CASE WHEN OBJECT_ID(N'dbo.K_NPCPOS_Z21_U3_BACKUP', N'U') IS NULL THEN 0 ELSE 1 END;
DECLARE @zone_info int = (SELECT COUNT(*) FROM dbo.ZONE_INFO WHERE ZoneNo = 21);
DECLARE @start int = (SELECT COUNT(*) FROM dbo.START_POSITION WHERE ZoneID = 21);
DECLARE @missing_mon int = (SELECT COUNT(*) FROM #u3_npcpos AS s
    WHERE s.ActType < 100 AND NOT EXISTS (SELECT 1 FROM dbo.K_MONSTER AS m WHERE m.sSid = s.NpcID));
DECLARE @missing_npc int = (SELECT COUNT(*) FROM #u3_npcpos AS s
    WHERE s.ActType >= 100 AND NOT EXISTS (SELECT 1 FROM dbo.K_NPC AS n WHERE n.sSid = s.NpcID));
DECLARE @deleted_obj int;
DECLARE @deleted_npc int;
DECLARE @inserted_obj int;
DECLARE @inserted_npc int;
DECLARE @backup varchar(10) = CASE WHEN @backups = 0 THEN 'created' ELSE 'kept' END;

IF DB_NAME() = N'FDP_kn_online'
BEGIN
    RAISERROR(N'this script is for the 1534 database copy, not FDP_kn_online; nothing changed', 16, 1);
    RETURN;
END
IF @obj_staged <> 3 OR @npc_staged <> 123
BEGIN
    RAISERROR(N'staging tables have %d/%d rows, expected 3/123; nothing changed', 16, 1, @obj_staged, @npc_staged);
    RETURN;
END
IF @backups NOT IN (0, 4)
BEGIN
    RAISERROR(N'%d of the 4 _Z21_U3_BACKUP tables exist (expected 0 or 4); nothing changed', 16, 1, @backups);
    RETURN;
END
IF @zone_info <> 1 OR @start <> 1
BEGIN
    RAISERROR(N'zone 21 has %d ZONE_INFO and %d START_POSITION rows (expected 1 and 1); nothing changed', 16, 1, @zone_info, @start);
    RETURN;
END
IF @missing_mon > 0 OR @missing_npc > 0
BEGIN
    RAISERROR(N'%d spawn rows name a monster missing in K_MONSTER and %d an NPC missing in K_NPC (apply db/014 first); nothing changed', 16, 1, @missing_mon, @missing_npc);
    RETURN;
END

BEGIN TRANSACTION;

-- Backups: only on the first run.
IF @backups = 0
BEGIN
    SELECT
        ServerNo, ZoneNo, strZoneName, InitX, InitZ, InitY, Type, RoomEvent, bz
    INTO dbo.ZONE_INFO_Z21_U3_BACKUP
    FROM dbo.ZONE_INFO
    WHERE ZoneNo = 21;

    SELECT
        ZoneID, sKarusX, sKarusZ, sElmoradX, sElmoradZ, sKarusGateX, sKarusGateZ,
        sElmoGateX, sElmoGateZ, bRangeX, bRangeZ
    INTO dbo.START_POSITION_Z21_U3_BACKUP
    FROM dbo.START_POSITION
    WHERE ZoneID = 21;

    SELECT
        ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
    INTO dbo.K_OBJECTPOS_Z21_U3_BACKUP
    FROM dbo.K_OBJECTPOS
    WHERE ZoneID = 21;

    SELECT
        ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
        LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
        NumNPC, RegTime, byDirection, DotCnt, path
    INTO dbo.K_NPCPOS_Z21_U3_BACKUP
    FROM dbo.K_NPCPOS
    WHERE ZoneID = 21;
END

-- ZONE_INFO and START_POSITION: update the zone-21 row in place.
UPDATE dbo.ZONE_INFO SET
    strZoneName = 'moradon_1534.smd',
    InitX = 81590,
    InitZ = 53079,
    InitY = 469,
    RoomEvent = 0
WHERE ZoneNo = 21;

UPDATE dbo.START_POSITION SET
    sKarusX = 817,
    sKarusZ = 530,
    sElmoradX = 817,
    sElmoradZ = 530,
    sKarusGateX = 0,
    sKarusGateZ = 0,
    sElmoGateX = 0,
    sElmoGateZ = 0,
    bRangeX = 10,
    bRangeZ = 10
WHERE ZoneID = 21;

-- K_OBJECTPOS and K_NPCPOS: replace the zone-21 rows.
DELETE FROM dbo.K_OBJECTPOS WHERE ZoneID = 21;
SET @deleted_obj = @@ROWCOUNT;

INSERT INTO dbo.K_OBJECTPOS (
    ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
)
SELECT
    ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
FROM #u3_objpos;
SET @inserted_obj = @@ROWCOUNT;

DELETE FROM dbo.K_NPCPOS WHERE ZoneID = 21;
SET @deleted_npc = @@ROWCOUNT;

INSERT INTO dbo.K_NPCPOS (
    ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber, LeftX,
    TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ, NumNPC, RegTime,
    byDirection, DotCnt, path
)
SELECT
    ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber, LeftX,
    TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ, NumNPC, RegTime,
    byDirection, DotCnt, path
FROM #u3_npcpos;
SET @inserted_npc = @@ROWCOUNT;

COMMIT TRANSACTION;

PRINT 'backup=' + @backup
    + ' deleted_objpos=' + CAST(@deleted_obj AS varchar(10))
    + ' deleted_npcpos=' + CAST(@deleted_npc AS varchar(10))
    + ' inserted_objpos=' + CAST(@inserted_obj AS varchar(10))
    + ' inserted_npcpos=' + CAST(@inserted_npc AS varchar(10));
GO

-- Verification: the zone-21 rows hold exactly the new values; the *_differ counts
-- compare the staged rows with the table rows as multisets (0 after a clean run).
DECLARE @zone_info int = (SELECT COUNT(*) FROM dbo.ZONE_INFO WHERE ZoneNo = 21
    AND strZoneName = 'moradon_1534.smd'
    AND InitX = 81590
    AND InitZ = 53079
    AND InitY = 469
    AND RoomEvent = 0);
DECLARE @start int = (SELECT COUNT(*) FROM dbo.START_POSITION WHERE ZoneID = 21
    AND sKarusX = 817
    AND sKarusZ = 530
    AND sElmoradX = 817
    AND sElmoradZ = 530
    AND sKarusGateX = 0
    AND sKarusGateZ = 0
    AND sElmoGateX = 0
    AND sElmoGateZ = 0
    AND bRangeX = 10
    AND bRangeZ = 10);
DECLARE @zone_info_rows int = (SELECT COUNT(*) FROM dbo.ZONE_INFO WHERE ZoneNo = 21);
DECLARE @start_rows int = (SELECT COUNT(*) FROM dbo.START_POSITION WHERE ZoneID = 21);
DECLARE @objpos int = (SELECT COUNT(*) FROM dbo.K_OBJECTPOS WHERE ZoneID = 21);
DECLARE @npcpos int = (SELECT COUNT(*) FROM dbo.K_NPCPOS WHERE ZoneID = 21);
DECLARE @obj_differ int =
    (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM #u3_objpos
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
        EXCEPT
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM dbo.K_OBJECTPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife) AS d)
    + (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM dbo.K_OBJECTPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife
        EXCEPT
        SELECT
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ,
            byLife, COUNT(*) AS n
        FROM #u3_objpos
        GROUP BY
            ZoneID, Belong, sIndex, Type, ControlNpcID, Status, PosX, PosY, PosZ, byLife) AS d);
DECLARE @npc_differ int =
    (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM #u3_npcpos
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))
        EXCEPT
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM dbo.K_NPCPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))) AS d)
    + (SELECT COUNT(*) FROM (
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM dbo.K_NPCPOS WHERE ZoneID = 21
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))
        EXCEPT
        SELECT
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max)) AS path,
            COUNT(*) AS n
        FROM #u3_npcpos
        GROUP BY
            ZoneID, NpcID, ActType, RegenType, DungeonFamily, SpecialType, TrapNumber,
            LeftX, TopZ, RightX, BottomZ, LimitMinX, LimitMinZ, LimitMaxX, LimitMaxZ,
            NumNPC, RegTime, byDirection, DotCnt, CAST(path AS varchar(max))) AS d);

PRINT 'zone_info=' + CAST(@zone_info AS varchar(10))
    + ' start=' + CAST(@start AS varchar(10))
    + ' objpos=' + CAST(@objpos AS varchar(10))
    + ' npcpos=' + CAST(@npcpos AS varchar(10))
    + ' objpos_differ=' + CAST(@obj_differ AS varchar(10))
    + ' npcpos_differ=' + CAST(@npc_differ AS varchar(10));

IF @zone_info <> 1 OR @zone_info_rows <> 1 OR @start <> 1 OR @start_rows <> 1
   OR @objpos <> 3 OR @npcpos <> 123 OR @obj_differ <> 0 OR @npc_differ <> 0
    RAISERROR(N'zone 21 does not hold the expected rows', 16, 1);

DROP TABLE #u3_objpos;
DROP TABLE #u3_npcpos;
GO
