#!/usr/bin/env python3
"""Generates db/012_u2_capes_1534.sql and db/012_u2_capes_1534_rollback.sql from the
1534 client cape table (Data/Cloak.tbl), decoded with tools/kotbl.py.

Column map of the 7-column 1534 Cloak.tbl (docs/reports/u0-1534/E-veri-farki.md 2.1):
    c0 -> sCapeIndex, c1 -> strName, c2 -> nBuyPrice, c3 -> nDuration,
    c4 -> byGrade, c5 -> nBuyLoyalty, c6 -> byRanking
The numeric values are taken from the client table as they are (not from the ALPHA
database). strName is not loaded by the server: an ASCII client name is kept; a Korean
one becomes "Cape <id>" plus the English pattern name when it is a known pattern.
Only the 7-column table is accepted; the 5-column table of the old client is an error.

Usage:
    python3 tools/u2-gen-capes.py [--client PATH]           # write both scripts
    python3 tools/u2-gen-capes.py [--client PATH] --check   # 0 = scripts in db/ are up to date

The client file is only read. Standard library only; works under python3 -I.
"""

import argparse
import hashlib
import importlib.util
import os
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(TOOLS_DIR)
DEFAULT_CLIENT = "/mnt/c/dev/fdp1534/client/Knight Online/Data/Cloak.tbl"
APPLY_NAME = "012_u2_capes_1534.sql"
ROLLBACK_NAME = "012_u2_capes_1534_rollback.sql"

COLUMNS = 7
NAME_WIDTH = 30  # KNIGHTS_CAPE.strName is char(30)
MAX_RANKING = 12  # ClanTypeRoyal1 (GameServer/Knights.h)
LONG_RANKING = (8, 12)  # the client draws the long (royal) cape mesh for ranking 8..12

# Korean pattern names of the x29..x33 capes (E report 2.2).
PATTERN_NAMES = {
    "\uc1e0\ucc3d\uc0b4": "iron bars",
    "\uc2ed\uc790\uac00": "cross",
    "\uccb4\ud06c\ubb34\ub2ac": "checkered",
    "\ub300\uce6d": "symmetric",
    "\uc30d\ub3c5\uc218\ub9ac": "double eagle",
}

# (column, SQL column, minimum, maximum)
NUMERIC = [
    (0, "sCapeIndex", 0, 32767),
    (2, "nBuyPrice", 0, 2147483647),
    (3, "nDuration", 0, 2147483647),
    (4, "byGrade", 0, 255),
    (5, "nBuyLoyalty", 0, 2147483647),
    (6, "byRanking", 0, MAX_RANKING),
]


class GenError(Exception):
    pass


def load_kotbl():
    # Load tools/kotbl.py by path: python3 -I does not put the script directory on sys.path.
    spec = importlib.util.spec_from_file_location("kotbl", os.path.join(TOOLS_DIR, "kotbl.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def is_plain_ascii(text):
    return all(0x20 <= ord(ch) < 0x7F for ch in text)


def cape_name(cape_id, client_name):
    name = client_name.strip()
    if name and is_plain_ascii(name):
        return name
    pattern = PATTERN_NAMES.get(name)
    if pattern:
        return "Cape %d %s" % (cape_id, pattern)
    return "Cape %d" % cape_id


def read_capes(kotbl, raw):
    table = kotbl.decode(raw)
    if table.columns != COLUMNS:
        raise GenError("Cloak.tbl has %d columns; only the %d-column 1534 client table is accepted"
                       " (the 5-column table belongs to the old client)" % (table.columns, COLUMNS))
    if table.types[1] != kotbl.TYPE_STRING:
        raise GenError("column 1 of Cloak.tbl is not a string column (types %s)" % table.types)
    for col, sql, _, _ in NUMERIC:
        if table.types[col] not in kotbl.INTEGER_TYPES:
            raise GenError("column %d (%s) is not an integer column (types %s)" % (col, sql, table.types))
    if table.trailing_bytes:
        raise GenError("Cloak.tbl has %d trailing bytes after the last row" % table.trailing_bytes)
    if table.bad_strings:
        raise GenError("Cloak.tbl has %d strings that are not valid CP949" % table.bad_strings)
    capes = {}
    for row in table.rows:
        for col, sql, low, high in NUMERIC:
            if not low <= row[col] <= high:
                raise GenError("cape %d: %s=%d is outside %d..%d" % (row[0], sql, row[col], low, high))
        cape_id = row[0]
        if cape_id in capes:
            raise GenError("cape id %d appears twice" % cape_id)
        name = cape_name(cape_id, row[1])
        if len(name) > NAME_WIDTH:
            raise GenError("cape %d: name %r is longer than %d characters" % (cape_id, name, NAME_WIDTH))
        capes[cape_id] = (cape_id, name, row[2], row[3], row[4], row[5], row[6])
    if not capes:
        raise GenError("Cloak.tbl has no rows")
    return [capes[k] for k in sorted(capes)]


def sql_string(text):
    return "'" + text.replace("'", "''") + "'"


def render_apply(capes, source):
    long_count = sum(1 for c in capes if LONG_RANKING[0] <= c[6] <= LONG_RANKING[1])
    values = ",\n".join("    (%d, %s, %d, %d, %d, %d, %d)" % (c[0], sql_string(c[1]), c[2], c[3], c[4], c[5], c[6])
                        for c in capes)
    return """-- 012_u2_capes_1534.sql
-- GENERATED by tools/u2-gen-capes.py from the 1534 client Data/Cloak.tbl.
-- Do not edit by hand; regenerate it and run the tool with --check instead.
-- Source: %(source)s
--
-- Purpose: add the capes that the 1534 client knows and the target table lacks
-- (phase U2, ADR-0068 item 4), including the long (royal) capes: the %(long)d rows
-- with byRanking 8..12. All values come from the client table, not from the
-- ALPHA database (its clan point prices and clan type requirements are wrong).
-- Column map: c0 sCapeIndex, c1 strName, c2 nBuyPrice, c3 nDuration,
-- c4 byGrade, c5 nBuyLoyalty, c6 byRanking. The server does not load strName;
-- Korean client names are written as "Cape <id>" (plus the pattern name).
--
-- Usage:
--   sqlcmd -S .\\SQLEXPRESS -E -d FDP_kn_online -b -v Target=KNIGHTS_CAPE -i db/012_u2_capes_1534.sql
--
-- The Target variable is required on purpose (no default); it names the cape
-- table. Only ids that the target does not have are inserted; existing rows are
-- never changed. Every inserted id is recorded in dbo.<Target>_U2_ADDED so that
-- 012_u2_capes_1534_rollback.sql can remove exactly those rows. The script is
-- idempotent: running it again inserts nothing (inserted=0).
-- The server loads the table only at start-up; restart it to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.$(Target)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(Target) not found', 16, 1);
GO

IF OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NULL
CREATE TABLE dbo.$(Target)_U2_ADDED
(
    sCapeIndex smallint NOT NULL PRIMARY KEY,
    dtAdded datetime NOT NULL DEFAULT GETDATE()
);
GO

-- The %(count)d capes of the client table.
DECLARE @capes TABLE
(
    sCapeIndex smallint NOT NULL PRIMARY KEY,
    strName char(30) NOT NULL,
    nBuyPrice int NOT NULL,
    nDuration int NOT NULL,
    byGrade tinyint NOT NULL,
    nBuyLoyalty int NOT NULL,
    byRanking tinyint NOT NULL
);

INSERT INTO @capes (sCapeIndex, strName, nBuyPrice, nDuration, byGrade, nBuyLoyalty, byRanking)
VALUES
%(values)s;

DECLARE @total int = (SELECT COUNT(*) FROM @capes);
DECLARE @inserted int;

BEGIN TRANSACTION;

-- Record the ids that are about to be inserted.
INSERT INTO dbo.$(Target)_U2_ADDED (sCapeIndex)
SELECT c.sCapeIndex
FROM @capes AS c
WHERE NOT EXISTS (SELECT 1 FROM dbo.$(Target) AS t WHERE t.sCapeIndex = c.sCapeIndex)
  AND NOT EXISTS (SELECT 1 FROM dbo.$(Target)_U2_ADDED AS a WHERE a.sCapeIndex = c.sCapeIndex);

-- Insert only the ids that the target does not have.
INSERT INTO dbo.$(Target) (sCapeIndex, strName, nBuyPrice, nDuration, byGrade, nBuyLoyalty, byRanking)
SELECT c.sCapeIndex, c.strName, c.nBuyPrice, c.nDuration, c.byGrade, c.nBuyLoyalty, c.byRanking
FROM @capes AS c
WHERE NOT EXISTS (SELECT 1 FROM dbo.$(Target) AS t WHERE t.sCapeIndex = c.sCapeIndex);

SET @inserted = @@ROWCOUNT;

COMMIT TRANSACTION;

PRINT 'inserted=' + CAST(@inserted AS varchar(10))
    + ' already_present=' + CAST(@total - @inserted AS varchar(10));
GO

-- Verification: one line with the row count of the target, its long capes
-- (byRanking 8..12) and the ids recorded in the log table.
DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(Target));
DECLARE @long int = (SELECT COUNT(*) FROM dbo.$(Target) WHERE byRanking BETWEEN 8 AND 12);
DECLARE @logged int = (SELECT COUNT(*) FROM dbo.$(Target)_U2_ADDED);
PRINT 'target_rows=' + CAST(@rows AS varchar(10))
    + ' long_capes=' + CAST(@long AS varchar(10))
    + ' logged=' + CAST(@logged AS varchar(10));
GO
""" % {"source": source, "long": long_count, "count": len(capes), "values": values}


def render_rollback(source):
    return """-- 012_u2_capes_1534_rollback.sql
-- GENERATED by tools/u2-gen-capes.py; do not edit by hand.
-- Source: %(source)s
--
-- Purpose: undo 012_u2_capes_1534.sql. Deletes only the ids recorded in
-- dbo.<Target>_U2_ADDED, then drops that log table. Rows that existed before
-- 012 was applied are never touched.
--
-- Usage:
--   sqlcmd -S .\\SQLEXPRESS -E -d FDP_kn_online -b -v Target=KNIGHTS_CAPE -i db/012_u2_capes_1534_rollback.sql
--
-- The Target variable is required on purpose (no default). The script can be
-- run again: without the log table it changes nothing (removed=0).
-- The server loads the table only at start-up; restart it to see the change.

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.$(Target)', N'U') IS NULL
    RAISERROR(N'target table dbo.$(Target) not found', 16, 1);
GO

DECLARE @removed int = 0;

IF OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NOT NULL
BEGIN
    BEGIN TRANSACTION;

    -- Remove only the rows that 012 inserted.
    DELETE t
    FROM dbo.$(Target) AS t
    JOIN dbo.$(Target)_U2_ADDED AS a
        ON a.sCapeIndex = t.sCapeIndex;

    SET @removed = @@ROWCOUNT;

    DROP TABLE dbo.$(Target)_U2_ADDED;

    COMMIT TRANSACTION;
END

DECLARE @rows int = (SELECT COUNT(*) FROM dbo.$(Target));
PRINT 'removed=' + CAST(@removed AS varchar(10))
    + ' target_rows=' + CAST(@rows AS varchar(10))
    + ' log_table=' + CASE WHEN OBJECT_ID(N'dbo.$(Target)_U2_ADDED', N'U') IS NULL THEN 'absent' ELSE 'present' END;
GO
""" % {"source": source}


def generate(client_path):
    kotbl = load_kotbl()
    with open(client_path, "rb") as f:
        raw = f.read()
    try:
        capes = read_capes(kotbl, raw)
    except kotbl.TableError as e:
        raise GenError("cannot decode %s: %s" % (client_path, e))
    source = "Data/Cloak.tbl, %d bytes, sha256 %s, %d rows, %d columns" % (
        len(raw), hashlib.sha256(raw).hexdigest(), len(capes), COLUMNS)
    outputs = {
        APPLY_NAME: render_apply(capes, source),
        ROLLBACK_NAME: render_rollback(source),
    }
    for name, text in outputs.items():
        try:
            text.encode("ascii")
        except UnicodeEncodeError:
            raise GenError("%s would not be ASCII" % name)
    return capes, {name: text.encode("ascii") for name, text in outputs.items()}


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate db/012 cape scripts from the 1534 client Cloak.tbl.")
    ap.add_argument("--client", default=DEFAULT_CLIENT, help="path of the 7-column Cloak.tbl")
    ap.add_argument("--check", action="store_true",
                    help="compare the generated scripts with db/ byte by byte (0 = identical)")
    args = ap.parse_args(argv)

    try:
        capes, outputs = generate(args.client)
    except (OSError, GenError) as e:
        sys.stderr.write("error: %s\n" % e)
        return 2
    db_dir = os.path.join(REPO_DIR, "db")
    long_count = sum(1 for c in capes if LONG_RANKING[0] <= c[6] <= LONG_RANKING[1])
    renamed = sum(1 for c in capes if c[1].startswith("Cape "))
    print("client capes=%d long_capes=%d ascii_names=%d generated_names=%d"
          % (len(capes), long_count, len(capes) - renamed, renamed))

    if args.check:
        differ = 0
        for name, data in outputs.items():
            path = os.path.join(db_dir, name)
            try:
                with open(path, "rb") as f:
                    current = f.read()
            except OSError:
                current = None
            if current == data:
                print("same: db/%s" % name)
            else:
                print("DIFFERENT: db/%s" % name)
                differ += 1
        print("check %s" % ("OK" if differ == 0 else "FAILED (%d file(s) differ)" % differ))
        return 0 if differ == 0 else 1

    for name, data in outputs.items():
        with open(os.path.join(db_dir, name), "wb") as f:
            f.write(data)
        print("wrote db/%s (%d bytes)" % (name, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
